services:
  php-fpm:
    build:
      context: ./docker-compose/php
      dockerfile: Dockerfile
    container_name: test-php-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app/:/var/www
      - ./docker-compose/php/entrypoint.sh:/var/entrypoint.sh
    ports:
      - "9000:9000"
    command: sh -c "set -x; /var/entrypoint.sh"
    networks:
      - test-task

  nginx:
    image: nginx:alpine
    container_name: test-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - test-task

networks:
  test-task:
    driver: bridge